### ISSUE TITLE
hugo-book 开启 disqus

### ISSUE THREAD

**Issue by zjp-CN** [kern-crates/hugo-book-template#2]
hugo-book 默认给文档开启了 disqus 评论区，但需要填写 shortname（子域名）。

```toml
# hugo.toml
[params]
  # (Optional, default true) Enables comments template on pages
  # By default partials/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = true

[services]
  [services.disqus]
    shortname = 'your-disqus-shortname'
```

因此只需要生成这个 disqus-shortname，完整步骤如下：

Hugo 文档：https://gohugo.io/content-management/comments/#configure-disqus

1. 注册一个 disqus 账号：https://disqus.com/profile/signup/

2. 在设置中添加网站
![Image](https://github.com/user-attachments/assets/eaf21e14-0072-4772-aece-e7b5a422b27c)

3. 输入网站名称，即 shortname
![Image](https://github.com/user-attachments/assets/bc4bb173-d222-45ac-95a2-60cc559e8ca7)

4. 回到设置，可以看到已经生成好了。并且可以在 `https://{shortname}.disqus.com/admin/` 管理这个网站。
![Image](https://github.com/user-attachments/assets/c8f16eff-584e-4b17-ae69-3a07c49f7d09)

5. 到 hugo.toml 中填写刚才的 shortname
